# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-16 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
