# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-17 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0002_auto_20200316_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='wait_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
