# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-18 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0003_appointment_wait_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='wait_time',
            field=models.IntegerField(null=True),
        ),
    ]
