# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-19 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0006_auto_20200319_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
